p2p/enr: parse ENRs with enode
ObolNetwork/charon pull request #1011
Opened 2022-08-21 15:07 UTC by dB2510

Corrects ENR encode/decode base64 format with the help of enode.

category: bug
ticket: #970

2022-08-21 15:09 UTC, corverroos commented on p2p/enr_test.go
> +	oldVersionENR := "enr:-HW4QHwvU8usykhaKQ_cxyAaAck_TlS0zr9nLNXDODQll87ifLECDsnczJz7vC_aVTKq9Q8aC3UIKWwls1i4TmEXLAuAgmlkgnY0iXNlY3AyNTZrMaEDhry2ryLc-Y39laN92yfixHghkWIjLeQ4orBvDQy20jA="
better do 1000 random ENRs

2022-08-21 15:15 UTC, corverroos commented on p2p/enr_test.go
> +	oldVersionENR := "enr:-HW4QHwvU8usykhaKQ_cxyAaAck_TlS0zr9nLNXDODQll87ifLECDsnczJz7vC_aVTKq9Q8aC3UIKWwls1i4TmEXLAuAgmlkgnY0iXNlY3AyNTZrMaEDhry2ryLc-Y39laN92yfixHghkWIjLeQ4orBvDQy20jA="
also see encoding/base64/base64_test.go:62

2022-08-21 15:18 UTC, corverroos approved these changes

2022-08-21 15:24 UTC, corverroos commented on p2p/enr.go
> +		enrStr = enrStr[:len(enrStr)-1]
this isn't correct

2022-08-21 17:16 UTC, dB2510 commented on p2p/enr.go
> +		enrStr = enrStr[:len(enrStr)-1]
why?

2022-08-21 17:29 UTC, dB2510 commented on p2p/enr.go
> +		enrStr = enrStr[:len(enrStr)-1]
got it

2022-08-22 09:34 UTC, corverroos commented
Just adding "do not merge" until we fully understand why things were not breaking sooner

2022-08-22 15:48 UTC, corverroos requested changes

2022-08-22 15:48 UTC, corverroos commented on cmd/createcluster.go
> +	}
don't understand why this is required

2022-08-22 15:48 UTC, corverroos commented on p2p/enr.go
> +	// Ensure backwards compatibility with older versions with encoded ENR strings.
add comment what that older actually did

2022-08-22 15:48 UTC, corverroos commented on p2p/enr_test.go
> +func encodeOldVersion(t *testing.T, r enr.Record) string {
add comment what this is

2022-08-22 15:48 UTC, corverroos commented on p2p/enr_test.go
> +	for i := 0; i < 1000; i++ {
100 is probably fine

2022-08-22 15:48 UTC, corverroos commented on testutil/compose/define.go
> +	}
doesn't seem right

2022-08-23 05:40 UTC, corverroos approved these changes

2022-08-23 06:11 UTC, merged