app: remove cluster_name from labels
ObolNetwork/charon pull request #1167
Opened 2022-09-25 19:24 UTC by xenowits

Remove `cluster_name` from default labels as we already have a unique identifier for cluster (`cluster_hash`). Moreover, `cluster_name` values are not supposed to be unique as they are user picked.

category: misc
ticket: none

2022-09-25 19:26 UTC, eth2devops approved these changes
LGTM

2022-09-26 06:29 UTC, corverroos requested changes
This is a nice to have, I'd keep it.

2022-09-26 11:12 UTC, closed without merging

2022-09-26 14:14 UTC, alysaleha commented
@corverroos @xenowits I agree that it is nice to have for while when we run a few hundreds of clusters, but when we run thousands of clusters it will be useless, as we will not care about names, and specially this label is not a unique id and can be repeated. Also removing it (and any extra labels) will optimize the cardinality.
What do you think guys?

2022-09-26 15:36 UTC, xenowits commented
> @corverroos @xenowits I agree that it is nice to have for while when we run a few hundreds of clusters, but when we run thousands of clusters it will be useless, as we will not care about names, and specially this label is not a unique id and can be repeated. Also removing it (and any extra labels) will optimize the cardinality. What do you think guys?

Aligned on less labels. I don't have any strong opinion to include/remove the label. I also wonder what value including this label brings