dkg: refactor dkg to reconnect to connecting phase
ObolNetwork/charon pull request #1495
Opened 2022-11-30 09:36 UTC by dB2510

Refactors dkg sync protocol to reconnect in connecting to peers phase.

category: refactor
ticket: #1475

2022-11-30 10:09 UTC, corverroos requested changes

2022-11-30 10:09 UTC, corverroos commented on dkg/dkg.go
>  	}
this isn't "once all peers are connected", rather this is "once all peers were connected once". 

Suggest:
 - `IsConnected` not blocking, but just return the current  status
 - refactor this to
   - check if all clients connected
   - if not, sleep for 100ms

2022-11-30 10:09 UTC, corverroos commented on dkg/sync/client.go
>  // or if an established connection is dropped. It returns nil after successful Shutdown.
godoc must the updated

2022-11-30 10:09 UTC, corverroos commented on dkg/sync/client.go
> +			if c.reconnect {
This retries always if reconnect is true, while the instruction state:
```
If c.reconnect=true, reconnect on either relayBroke or connBroke with retry=true.
If c.reconnect=false, only reconnect on relayBroke with retry=false.
```

2022-11-30 10:13 UTC, corverroos commented on dkg/dkg_test.go
> +			name:       "first",
not very discriptive

2022-11-30 10:17 UTC, corverroos commented on dkg/dkg_test.go
> +			dkgs := make([]*testDkg, nodes)
canonical slice initialisation: `var dkgs []*testDkg`

2022-11-30 10:17 UTC, corverroos commented on dkg/dkg_test.go
> +			time.Sleep(time.Second * 5) // Give some time to connect.
not a fan of sleeping. Since it is brittle and will flap. Rather wait for callbacks.

2022-11-30 10:17 UTC, corverroos commented on dkg/dkg_test.go
> +			require.NoError(t, os.RemoveAll(dir))
no need to delete test dirs (you might not have perms)

2022-11-30 10:17 UTC, corverroos commented on dkg/dkg_test.go
> +	}
move this into the loop to avoid having to think and worry about mutable state.

2022-12-06 11:18 UTC, corverroos commented on dkg/dkg_test.go
> +			dkgs := make([]*testDkg, nodes)
add comment maybe?

2022-12-06 11:19 UTC, dB2510 commented on dkg/dkg_test.go
> +			dkgs := make([]*testDkg, nodes)
sure

2022-12-07 14:17 UTC, corverroos commented on dkg/dkg.go
> +		connectedCount := 0
`var count int`

2022-12-08 15:29 UTC, merged