cmd: remove deprecated flags from relay command
ObolNetwork/charon pull request #1635
Opened 2023-01-16 15:49 UTC by xenowits

Removes deprecated flags from `charon relay` command.

category: refactor
ticket: none

2023-01-16 15:50 UTC, xenowits commented
@OisinKyne https://github.com/ObolNetwork/obol-docs/pull/98#discussion_r1071298000

2023-01-16 16:05 UTC, corverroos requested changes

2023-01-16 16:05 UTC, corverroos commented on cmd/relay.go
> +	cmd.Flags().BoolVar(&config.DisableReuseport, "p2p-disable-reuseport", false, "Disables TCP port reuse for outgoing libp2p connections.")
can remove this, not used by relays

2023-01-16 16:05 UTC, corverroos commented on cmd/relay.go
> +	cmd.Flags().StringVar(&config.Denylist, "p2p-denylist", "", "Comma-separated list of CIDR subnets for disallowing certain peer connections. Example: 192.168.0.0/16 would disallow connections to peer
can remove allow/denylist not used by relay

2023-01-16 16:05 UTC, corverroos commented on cmd/relay.go
> +	cmd.Flags().StringSliceVar(&relays, "p2p-relays", []string{"http://bootnode.lb.gcp.obol.tech:3640/enr"}, "Comma-separated list of libp2p relay URLs or ENRs.")
can remove this, not used by relays

2023-01-16 16:12 UTC, xenowits commented
Updated output:

<img width="1463" alt="Screenshot 2023-01-16 at 21 41 50" src="https://user-images.githubusercontent.com/43061995/212722834-034debba-5fd0-4af9-9ee0-8cb66a496ca8.png">

2023-01-16 16:23 UTC, corverroos commented on cmd/relay.go
> +func bindP2PFlagsRelay(cmd *cobra.Command, config *p2p.Config) {
can't remove `p2p-udp-address` yet since it needs to support it for older clusters.

2023-01-16 16:36 UTC, xenowits commented
Update output:

<img width="1448" alt="Screenshot 2023-01-16 at 22 06 34" src="https://user-images.githubusercontent.com/43061995/212727413-28882703-f18a-48d3-95c2-af97827b6260.png">

2023-01-17 05:46 UTC, xenowits commented
Closing this since the `relay` feature isn't much tested so we can remove the deprecated flags in the next release, ie, v0.14.0. We could also deprecate the `charon bootnode` command fully in v0.14.0

2023-01-17 05:46 UTC, closed without merging