app: add gauge for upstream beacon node version
ObolNetwork/charon pull request #1825
Opened 2023-02-20 15:48 UTC by xenowits

Adds a constant gauge with label set to the upstream beacon node version. It is refreshed every 10mins. 

Also updates a new panel for beacon node metrics to simnet grafana dashboard.

category: feature
ticket: #1773

2023-02-20 15:49 UTC, xenowits commented
See the panel titled `Beacon node` in the following sample compose dashboard:

<img width="1858" alt="Screenshot 2023-02-20 at 21 12 54" src="https://user-images.githubusercontent.com/43061995/220150880-0f0c896d-4c1b-4a34-9d0b-d1fc91dd26b5.png">

2023-02-20 16:37 UTC, corverroos requested changes

2023-02-20 16:37 UTC, corverroos commented on app/monitoringapi.go
> +		beaconNodeVersionGauge.WithLabelValues(version).Set(1)
see the warning I added to the issue: https://github.com/ObolNetwork/charon/issues/1773#issuecomment-1423718659

2023-02-22 10:43 UTC, corverroos commented on app/monitoringapi.go
> +	prevNodeVersion := ""
`var prevNodeVersion string`

2023-02-22 10:43 UTC, corverroos approved these changes

2023-02-22 14:44 UTC, merged