cmd: write deposit datas to disk
ObolNetwork/charon pull request #2395
Opened 2023-07-04 09:09 UTC by xenowits

Write deposit data file for new validators created in `add-validators-solo` command to each node directory.

category: feature 
ticket: #2379

2023-07-04 11:46 UTC, corverroos requested changes

2023-07-04 11:46 UTC, corverroos commented on cmd/addvalidators.go
> +func writeManifestBackups(clusterDir string, numOps int, cluster *manifestpb.Cluster, currTime string) error {
remove backups as discussed

2023-07-04 11:46 UTC, corverroos commented on cmd/addvalidators.go
> +	filename := fmt.Sprintf("deposit-data-%s.pb", currTime) // Ex: "cluster-manifest-backup-20060102150405.pb"
remove timestamp

2023-07-04 11:54 UTC, corverroos commented on cmd/addvalidators.go
> +	filename := fmt.Sprintf("deposit-data-%s.pb", currTime) // Ex: "cluster-manifest-backup-20060102150405.pb"
we need to log that this is the new deposit datas that was created

2023-07-05 12:53 UTC, corverroos approved these changes

2023-07-05 12:53 UTC, corverroos commented on cmd/addvalidators.go
> +	cluster, _, err := loadClusterManifest(conf)
add TODO to loadClusterManifest to remove the boolean since it is never used

2023-07-05 12:53 UTC, corverroos commented on cmd/addvalidators.go
> +			return []*manifestpb.Validator{}, []tbls.PrivateKey{}, errors.Wrap(err, "generate secret key")
can return nil, nil, errors.Wrap

2023-07-05 13:00 UTC, gsora approved these changes

2023-07-05 13:59 UTC, merged