eth2util/keymanager: dynamically set keymanager POST request timeout
ObolNetwork/charon pull request #2586
Opened 2023-09-13 11:41 UTC by eth2353

Using the `--keymanager-addresses` flag to automatically import keystores fails when creating a cluster with more than a handful of keystores due to the request timing out while the remote signer is importing the keystores.

This PR adjusts the behavior by making the timeout value dependent on the amount of keystores to be imported, setting a timeout of 2 seconds per keystore. This value was chosen rather arbitrarily as a "safe", high enough value based on my experience with importing keystores, this taking around 0.25 - 0.5 seconds per keystore.

Feel free to lower the value as you deem fit. However, the request timing out can be rather annoying to resolve, since the entire `create cluster` process needs to be started over and keystores need to manually be removed from keymanagers where they were already imported. This is why I propose to use a safe, albeit little high, timeout value.

category: bug
ticket: none

2023-10-16 08:25 UTC, xenowits approved these changes

2023-10-16 08:28 UTC, gsora requested changes

2023-10-16 08:28 UTC, gsora commented on eth2util/keymanager/keymanager.go
>  // postKeys pushes the secrets to the provided keymanager address. The HTTP request times out after 10s.
```suggestion
// postKeys pushes the secrets to the provided keymanager address. The HTTP request timeout is calculated based on the amount of keystores being pushed. For each keystore, the timeout is incremented by 2 seconds.
```

2023-10-24 08:06 UTC, gsora approved these changes

2023-10-24 08:06 UTC, merged